### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by supershanefx** [simsalabim/dsweeper#10]
When I run the dsweeper -d  Im getting the following error

TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/dsweeper/bin/dsweeper:11:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

**Comment by simsalabim** [comment]
Sorry to hear that, but your bug report doesn't say much about the environment you're running dsweeper in. What OS, node/npm are you using? Also, looking at the stacktrace you posted I assume you have your dropbox `info.json` located in an unexpected directory. See https://github.com/simsalabim/dsweeper/blob/master/bin/dsweeper#L11
